if exists (select * from sys.objects where name='APPLICATION_PRODUCT' and type='U')
	drop table IL.APPLICATION_PRODUCT
GO

CREATE TABLE IL.APPLICATION_PRODUCT (
	ID 						int IDENTITY(1, 1)	NOT NULL,
	APPLICATION_ID			uniqueidentifier	NOT NULL,
	DESCRIPTION				nvarchar(150)		NULL,
	QUANTITY				int					NOT NULL,
	PRICE					money				NULL,
	PRODUCT_CATEGORY_CODE	char(2)				NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_PRODUCT1 ON IL.APPLICATION_PRODUCT(APPLICATION_ID, ID)
GO
