if exists (select * from sys.objects where name='BANK_USER' and type='U')
	drop table IL.BANK_USER
GO

CREATE TABLE IL.BANK_USER (
	APPLICATION_USER_ID	int	NOT NULL,
	IS_ADMINISTRATOR	bit	NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iBANK_USER1 ON IL.BANK_USER(APPLICATION_USER_ID)
GO
