if exists (select * from sys.objects where name='GOODS_RECEIVING_OPTIONS' and type='U')
	drop table IL.GOODS_RECEIVING_OPTIONS
GO

CREATE TABLE IL.GOODS_RECEIVING_OPTIONS (
	CODE 	char(1)			NOT NULL,
	NAME_AM	nvarchar(50)	NOT NULL,
	NAME_EN	varchar(50)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iGOODS_RECEIVING_OPTIONS1 ON IL.GOODS_RECEIVING_OPTIONS(CODE)
GO
