if exists (select * from sys.objects where name='SHOP_USER' and type='U')
	drop table IL.SHOP_USER
GO

CREATE TABLE IL.SHOP_USER (
	APPLICATION_USER_ID		int				NOT NULL,
	SHOP_CODE				char(4)			NOT NULL,
	IS_MANAGER				bit				NOT NULL,
	MOBILE_PHONE			varchar(20)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iSHOP_USER1 ON IL.SHOP_USER(APPLICATION_USER_ID)
GO

CREATE INDEX iSHOP_USER2 ON IL.SHOP_USER(SHOP_CODE)
GO
