if exists (select * from sys.objects where name='SHOP_CATEGORY' and type='U')
	drop table IL.SHOP_CATEGORY
GO

CREATE TABLE IL.SHOP_CATEGORY (
	SHOP_CODE				char(4)	NOT NULL,
	PRODUCT_CATEGORY_CODE	char(2)	NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iSHOP_CATEGORY1 ON IL.SHOP_CATEGORY(SHOP_CODE,PRODUCT_CATEGORY_CODE)
GO
