if exists (select * from sys.objects where name='AGREED_APPLICATION' and type='U')
	drop table GL.AGREED_APPLICATION
GO

CREATE TABLE GL.AGREED_APPLICATION (
	CREATION_DATE			datetime			NOT NULL default getdate(),
	APPLICATION_ID 			uniqueidentifier	NOT NULL,
	EXISTING_CARD_CODE		char(16)			NULL,
	IS_NEW_CARD				bit					NULL,
	CREDIT_CARD_TYPE_CODE	char(3)				NULL,
	IS_CARD_DELIVERY		bit					NULL,
	CARD_DELIVERY_ADDRESS	nvarchar(150)		NULL,
	BANK_BRANCH_CODE		char(3)				NULL,
	IS_ARBITRAGE_CHECKED	bit					NULL,
	ACTUAL_INTEREST			money				NULL,
	PLEDGE_AGREEMENT_DATE	datetime			NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAGREED_APPLICATION1 ON GL.AGREED_APPLICATION(APPLICATION_ID)
GO
