if exists (select * from sys.objects where name='WORKING_EXPERIENCE' and type='U')
	drop table GL.WORKING_EXPERIENCE
GO

CREATE TABLE GL.WORKING_EXPERIENCE (
	CODE 	char(1)			NOT NULL,
	NAME_AM	nvarchar(50)	NOT NULL,
	NAME_EN	varchar(50)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iWORKING_EXPERIENCE1 ON GL.WORKING_EXPERIENCE(CODE)
GO
