export { default as IdentityDocuments } from './IdentityDocuments';
export { default as PersonalDetails } from './PersonalDetails';
export { default as WorkingDetails } from './WorkingDetails';
export { default as AddressDetails } from './AddressDetails';
export { default as NameSurName } from './NameSurName';
export { default as Citizenship } from './Citizenship';
export { default as Documents } from './Documents';
export { default as FieldSet } from './FieldSet';
export { default as UniversityDetails } from './UniversityDetails';
