ALTER TABLE Common.COMPLETED_APPLICATION
ADD
	BRANCH_CODE					varchar(3)			NULL,
	USER_ID						varchar(4)			NULL
GO



create or alter procedure Common.sp_SaveCompletedApplication(
	@APPLICATION_ID 			uniqueidentifier,
	@INTEREST					money = null,
	@FINAL_AMOUNT				money = null,
	@PERIOD_TYPE_CODE			char(3) = null,
	@REPAY_DAY					tinyint = null,
	@GOODS_RECEIVING_CODE		char(1) = null,
	@GOODS_DELIVERY_ADDRESS		nvarchar(150) = null,
	@FIRST_NAME_EN				varchar(20) = null,
	@LAST_NAME_EN				varchar(20) = null,
	@MOBILE_PHONE_1				varchar(20) = null,
	@MOBILE_PHONE_2				varchar(20) = null,
	@FIXED_PHONE				varchar(20) = null,
	@EMAIL						varchar(70) = null,
	@BIRTH_PLACE_CODE			char(2) = null,
	@CITIZENSHIP_CODE			char(2) = null,
	@REGISTRATION_COUNTRY_CODE	char(2) = null,
	@REGISTRATION_STATE_CODE	char(3) = null,
	@REGISTRATION_CITY_CODE		char(9) = null,
	@REGISTRATION_STREET		nvarchar(150) = null,
	@REGISTRATION_BUILDNUM		nvarchar(30) = null,
	@REGISTRATION_APARTMENT		nvarchar(30) = null,
	@CURRENT_COUNTRY_CODE		char(2) = null,
	@CURRENT_STATE_CODE			char(3) = null,
	@CURRENT_CITY_CODE			char(9) = null,
	@CURRENT_STREET				nvarchar(150) = null,
	@CURRENT_BUILDNUM			nvarchar(30) = null,
	@CURRENT_APARTMENT			nvarchar(30) = null,
	@COMMUNICATION_TYPE_CODE	char(1) = null,
	@COMPANY_NAME				nvarchar(40) = null,
	@COMPANY_PHONE				varchar(20) = null,
	@POSITION					nvarchar(50) = null,
	@MONTHLY_INCOME_CODE		char(1) = null,
	@WORKING_EXPERIENCE_CODE	char(1)	= null,
	@FAMILY_STATUS_CODE			char(1)	= null,
	@SHOP_CODE					char(4) = null,
	@SHOP_USER_ID				int	= null,
	@PRODUCT_CATEGORY_CODE		char(2) = null,
	@PRODUCT_NUMBER				varchar(20) = null,
	@LOAN_TEMPLATE_CODE			char(4)	= null,
	@OVERDRAFT_TEMPLATE_CODE	char(4)	= null,
	@IS_CURRENT_ADDRESS_SAME	bit	= null,

	@AUTO_BRAND_NAME					nvarchar(100) = NULL,
	@AUTO_VIN_CODE						varchar(17) = NULL,
	@AUTO_PRODUCTION_YEAR				smallint = NULL,
	@AUTO_OWNERSHIP_CERTIFCATE_DATE		date = NULL,
	@AUTO_OWNERSHIP_CERTIFCATE_NUMBER	nvarchar(20) = NULL,

	@ESTATE_ADDRESS						nvarchar(140) = NULL,
	@ESTATE_RESIDENTIAL_AREA			money = NULL,
	@ESTATE_LAND_AREA					money = NULL,

	@PLEDGE_PRICE				money = null,
	@INSURANCE_COMPANY_CODE		char(3) = null,
	@PLEDGE_TYPE_ACRA			char(2)	= NULL,
	@PLEDGE_TYPE_LR				char(2)	= NULL,

	@DEVELOPER_CODE				varchar(8) = NULL,
	@DEVELOPER_DELTA			bit = NULL,
	@DEVELOPER_AMOUNT			money = NULL,
	@DEVELOPER_INTEREST			money = NULL,
	@COMPLETION_DATE			date = NULL,

	@PREPAID_AMOUNT				money = NULL,
	@LTV						money = NULL,

	@BRANCH_CODE				varchar(3) = NULL,
	@USER_ID					varchar(4) = NULL,

	@OPERATION_DETAILS			nvarchar(max),
	@IS_SUBMIT					bit
)
AS
	BEGIN TRANSACTION

	BEGIN TRY
		declare @STATUS tinyint, @CUSTOMER_USER_ID int, @PARTNER_COMPANY_CODE varchar(8), @LOAN_TYPE_ID char(2), @IMPORT_ID int

		select @STATUS = STATUS, @CUSTOMER_USER_ID = CUSTOMER_USER_ID, @PARTNER_COMPANY_CODE = PARTNER_COMPANY_CODE, @LOAN_TYPE_ID = LOAN_TYPE_ID, @IMPORT_ID = IMPORT_ID
		from Common.APPLICATION with (updlock) where ID = @APPLICATION_ID

		if not @STATUS in (5, 8)
			RAISERROR (N'Հայտը տվյալների լրացման կարգավիճակում չէ', 17, 1)

		if not @SHOP_USER_ID is null
			update Common.APPLICATION set SHOP_USER_ID = @SHOP_USER_ID where ID = @APPLICATION_ID
		else
			select @SHOP_USER_ID = SHOP_USER_ID from Common.APPLICATION with (updlock) where ID = @APPLICATION_ID

		if @SHOP_CODE is null and not @PARTNER_COMPANY_CODE is null
			select @SHOP_CODE = SHOP_CODE from Common.PARTNER_COMPANY where CODE = @PARTNER_COMPANY_CODE

		insert into Common.APPLICATION_OPERATION_LOG
				(CUSTOMER_USER_ID, SHOP_USER_ID, PARTNER_COMPANY_CODE, LOAN_TYPE_ID, OPERATION_CODE, APPLICATION_ID, OPERATION_DETAILS)
			values
				(@CUSTOMER_USER_ID, @SHOP_USER_ID, @PARTNER_COMPANY_CODE, @LOAN_TYPE_ID, 'EDIT', @APPLICATION_ID, @OPERATION_DETAILS)

		delete from Common.COMPLETED_APPLICATION where APPLICATION_ID = @APPLICATION_ID
		insert into Common.COMPLETED_APPLICATION
			(APPLICATION_ID,INTEREST,FINAL_AMOUNT,PERIOD_TYPE_CODE,REPAY_DAY,GOODS_RECEIVING_CODE,GOODS_DELIVERY_ADDRESS,FIRST_NAME_EN,LAST_NAME_EN,MOBILE_PHONE_1,MOBILE_PHONE_2,FIXED_PHONE,EMAIL,BIRTH_PLACE_CODE,CITIZENSHIP_CODE
				,REGISTRATION_COUNTRY_CODE,REGISTRATION_STATE_CODE,REGISTRATION_CITY_CODE,REGISTRATION_STREET,REGISTRATION_BUILDNUM,REGISTRATION_APARTMENT
				,CURRENT_COUNTRY_CODE,CURRENT_STATE_CODE,CURRENT_CITY_CODE,CURRENT_STREET,CURRENT_BUILDNUM,CURRENT_APARTMENT
				,COMMUNICATION_TYPE_CODE,COMPANY_NAME,COMPANY_PHONE,POSITION,MONTHLY_INCOME_CODE,WORKING_EXPERIENCE_CODE,FAMILY_STATUS_CODE,SHOP_CODE,PRODUCT_CATEGORY_CODE,PRODUCT_NUMBER,LOAN_TEMPLATE_CODE,OVERDRAFT_TEMPLATE_CODE
				,IS_CURRENT_ADDRESS_SAME,AUTO_BRAND_NAME,AUTO_VIN_CODE,AUTO_PRODUCTION_YEAR,AUTO_OWNERSHIP_CERTIFCATE_DATE,AUTO_OWNERSHIP_CERTIFCATE_NUMBER,ESTATE_ADDRESS,ESTATE_RESIDENTIAL_AREA,ESTATE_LAND_AREA
				,PLEDGE_PRICE,INSURANCE_COMPANY_CODE,PLEDGE_TYPE_ACRA,PLEDGE_TYPE_LR,DEVELOPER_CODE,DEVELOPER_DELTA,DEVELOPER_AMOUNT,DEVELOPER_INTEREST,COMPLETION_DATE,PREPAID_AMOUNT,LTV,BRANCH_CODE,USER_ID)
		values
			(@APPLICATION_ID,@INTEREST,@FINAL_AMOUNT,@PERIOD_TYPE_CODE,@REPAY_DAY,@GOODS_RECEIVING_CODE,@GOODS_DELIVERY_ADDRESS,@FIRST_NAME_EN,@LAST_NAME_EN,@MOBILE_PHONE_1,@MOBILE_PHONE_2,@FIXED_PHONE,@EMAIL,@BIRTH_PLACE_CODE,@CITIZENSHIP_CODE
				,@REGISTRATION_COUNTRY_CODE,@REGISTRATION_STATE_CODE,@REGISTRATION_CITY_CODE,@REGISTRATION_STREET,@REGISTRATION_BUILDNUM,@REGISTRATION_APARTMENT
				,@CURRENT_COUNTRY_CODE,@CURRENT_STATE_CODE,@CURRENT_CITY_CODE,@CURRENT_STREET,@CURRENT_BUILDNUM,@CURRENT_APARTMENT
				,@COMMUNICATION_TYPE_CODE,@COMPANY_NAME,@COMPANY_PHONE,@POSITION,@MONTHLY_INCOME_CODE,@WORKING_EXPERIENCE_CODE,@FAMILY_STATUS_CODE,@SHOP_CODE,@PRODUCT_CATEGORY_CODE,@PRODUCT_NUMBER,@LOAN_TEMPLATE_CODE,@OVERDRAFT_TEMPLATE_CODE
				,@IS_CURRENT_ADDRESS_SAME,@AUTO_BRAND_NAME,@AUTO_VIN_CODE,@AUTO_PRODUCTION_YEAR,@AUTO_OWNERSHIP_CERTIFCATE_DATE,@AUTO_OWNERSHIP_CERTIFCATE_NUMBER,@ESTATE_ADDRESS,@ESTATE_RESIDENTIAL_AREA,@ESTATE_LAND_AREA
				,@PLEDGE_PRICE,@INSURANCE_COMPANY_CODE,@PLEDGE_TYPE_ACRA,@PLEDGE_TYPE_LR,@DEVELOPER_CODE,@DEVELOPER_DELTA,@DEVELOPER_AMOUNT,@DEVELOPER_INTEREST,@COMPLETION_DATE,@PREPAID_AMOUNT,@LTV,@BRANCH_CODE,@USER_ID)

		if @IS_SUBMIT=1
		begin
			execute Common.sp_ChangeApplicationStatus @APPLICATION_ID,10

			if @IMPORT_ID>0
				update Common.APPLICATION
					set STATUS=16,TO_BE_SYNCHRONIZED=1
				where IMPORT_ID=@IMPORT_ID and ID<>@APPLICATION_ID
		end

		if @LOAN_TYPE_ID = '00'
			execute IL.sp_UpdateShopSequenceNumber @APPLICATION_ID

		if not @CUSTOMER_USER_ID is null
			update Common.CUSTOMER_USER set
				FIRST_NAME_EN				= isnull(@FIRST_NAME_EN,				FIRST_NAME_EN),
				LAST_NAME_EN				= isnull(@LAST_NAME_EN,					LAST_NAME_EN),
				MOBILE_PHONE				= isnull(@MOBILE_PHONE_1,				MOBILE_PHONE),
				FIXED_PHONE					= isnull(@FIXED_PHONE,					FIXED_PHONE),
				EMAIL						= isnull(@EMAIL,						EMAIL),
				BIRTH_PLACE_CODE 			= isnull(@BIRTH_PLACE_CODE, 			BIRTH_PLACE_CODE),
				CITIZENSHIP_CODE			= isnull(@CITIZENSHIP_CODE,				CITIZENSHIP_CODE),

				REGISTRATION_COUNTRY_CODE	= isnull(@REGISTRATION_COUNTRY_CODE,	REGISTRATION_COUNTRY_CODE),
				REGISTRATION_STATE_CODE		= isnull(@REGISTRATION_STATE_CODE,		REGISTRATION_STATE_CODE),
				REGISTRATION_CITY_CODE		= isnull(@REGISTRATION_CITY_CODE,		REGISTRATION_CITY_CODE),
				REGISTRATION_STREET			= isnull(@REGISTRATION_STREET,			REGISTRATION_STREET),
				REGISTRATION_BUILDNUM		= isnull(@REGISTRATION_BUILDNUM,		REGISTRATION_BUILDNUM),
				REGISTRATION_APARTMENT		= isnull(@REGISTRATION_APARTMENT,		REGISTRATION_APARTMENT),
				CURRENT_COUNTRY_CODE		= isnull(@CURRENT_COUNTRY_CODE,			CURRENT_COUNTRY_CODE),
				CURRENT_STATE_CODE			= isnull(@CURRENT_STATE_CODE,			CURRENT_STATE_CODE),
				CURRENT_CITY_CODE			= isnull(@CURRENT_CITY_CODE,			CURRENT_CITY_CODE),
				CURRENT_STREET				= isnull(@CURRENT_STREET,				CURRENT_STREET),
				CURRENT_BUILDNUM			= isnull(@CURRENT_BUILDNUM,				CURRENT_BUILDNUM),
				CURRENT_APARTMENT			= isnull(@CURRENT_APARTMENT,			CURRENT_APARTMENT),

				COMPANY_NAME				= isnull(@COMPANY_NAME,					COMPANY_NAME),
				COMPANY_PHONE				= isnull(@COMPANY_PHONE,				COMPANY_PHONE),
				POSITION					= isnull(@POSITION,						POSITION),
				MONTHLY_INCOME_CODE			= isnull(@MONTHLY_INCOME_CODE,			MONTHLY_INCOME_CODE),
				WORKING_EXPERIENCE_CODE		= isnull(@WORKING_EXPERIENCE_CODE, 		WORKING_EXPERIENCE_CODE),
				FAMILY_STATUS_CODE			= isnull(@FAMILY_STATUS_CODE,			FAMILY_STATUS_CODE)
			where APPLICATION_USER_ID = @CUSTOMER_USER_ID

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage nvarchar(4000) = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
	END CATCH
GO



CREATE OR ALTER PROCEDURE Common.sp_GetMainApplicationFromBank(@ID	uniqueidentifier)
AS
	select
		c.FINAL_AMOUNT,
		isnull(c.INTEREST,0) as INTEREST,
		c.PERIOD_TYPE_CODE,
		c.REPAY_DAY,
		isnull(c.FIRST_NAME_EN,'') as FIRST_NAME_EN,
		isnull(c.LAST_NAME_EN,'') as LAST_NAME_EN,
		coalesce(a.MOBILE_PHONE_1,c.MOBILE_PHONE_1,u.MOBILE_PHONE) as MOBILE_PHONE_1,
		isnull(c.MOBILE_PHONE_2,'') as MOBILE_PHONE_2,
		coalesce(c.FIXED_PHONE,u.FIXED_PHONE,'') as FIXED_PHONE,
		coalesce(c.EMAIL,u.EMAIL,'') as EMAIL,
		isnull(c.BIRTH_PLACE_CODE,'') as BIRTH_PLACE_CODE,
		isnull(c.CITIZENSHIP_CODE,'') as CITIZENSHIP_CODE,
		isnull(c.REGISTRATION_COUNTRY_CODE,'') as REGISTRATION_COUNTRY_CODE,
		isnull(c.REGISTRATION_STATE_CODE,'') as REGISTRATION_STATE_CODE,
		isnull(c.REGISTRATION_CITY_CODE,'') as REGISTRATION_COMMUNITY,
		isnull(Common.ahf_Unicode2ANSI(c.REGISTRATION_STREET),'') as REGISTRATION_STREET,
		isnull(Common.ahf_Unicode2ANSI(c.REGISTRATION_BUILDNUM),'') as REGISTRATION_BUILDNUM,
		isnull(Common.ahf_Unicode2ANSI(c.REGISTRATION_APARTMENT),'') as REGISTRATION_APARTMENT,
		isnull(c.CURRENT_COUNTRY_CODE,'') as CURRENT_COUNTRY_CODE,
		isnull(c.CURRENT_STATE_CODE,'') as CURRENT_STATE_CODE,
		isnull(c.CURRENT_CITY_CODE,'') as CURRENT_COMMUNITY,
		isnull(Common.ahf_Unicode2ANSI(c.CURRENT_STREET),'') as CURRENT_STREET,
		isnull(Common.ahf_Unicode2ANSI(c.CURRENT_BUILDNUM),'') as CURRENT_BUILDNUM,
		isnull(Common.ahf_Unicode2ANSI(c.CURRENT_APARTMENT),'') as CURRENT_APARTMENT,
		isnull(Common.ahf_Unicode2ANSI(c.COMPANY_NAME),'') as COMPANY_NAME,
		isnull(c.COMPANY_PHONE,'') as COMPANY_PHONE,
		isnull(Common.ahf_Unicode2ANSI(c.POSITION),'') as POSITION,
		isnull(c.MONTHLY_INCOME_CODE,'') as MONTHLY_INCOME_CODE,
		isnull(c.WORKING_EXPERIENCE_CODE,'') as WORKING_EXPERIENCE_CODE,
		isnull(c.FAMILY_STATUS_CODE,'') as FAMILY_STATUS_CODE,
		isnull(c.SHOP_CODE,'') as SHOP_CODE,
		coalesce(a.PRODUCT_CATEGORY_CODE,c.PRODUCT_CATEGORY_CODE,'') as PRODUCT_CATEGORY_CODE,
		isnull(c.PRODUCT_NUMBER,'') as PRODUCT_NUMBER,
		isnull(c.GOODS_RECEIVING_CODE,'') as GOODS_RECEIVING_CODE,
		isnull(c.GOODS_DELIVERY_ADDRESS,'') as GOODS_DELIVERY_ADDRESS,
		coalesce(a.LOAN_TEMPLATE_CODE,c.LOAN_TEMPLATE_CODE,'') as LOAN_TEMPLATE_CODE,
		isnull(c.OVERDRAFT_TEMPLATE_CODE,'') as OVERDRAFT_TEMPLATE_CODE,
		isnull(c.SHOP_SEQUENCE_NUMBER,'') as SHOP_SEQUENCE_NUMBER,
		isnull(ag.EXISTING_CARD_CODE,'') as EXISTING_CARD_CODE,
		isnull(ag.IS_NEW_CARD,0) as IS_NEW_CARD,
		isnull(ag.CREDIT_CARD_TYPE_CODE,'') as CREDIT_CARD_TYPE_CODE,
		isnull(ag.IS_CARD_DELIVERY,0) as IS_CARD_DELIVERY,
		isnull(Common.ahf_Unicode2ANSI(ag.CARD_DELIVERY_ADDRESS),'') as CARD_DELIVERY_ADDRESS,
		isnull(ag.BANK_BRANCH_CODE,'') as BANK_BRANCH_CODE,
		isnull(c.COMMUNICATION_TYPE_CODE,'') as COMMUNICATION_TYPE_CODE,
		isnull(ag.IS_ARBITRAGE_CHECKED,0) as IS_ARBITRAGE_CHECKED,
		isnull(c.IS_CURRENT_ADDRESS_SAME,0) as IS_CURRENT_ADDRESS_SAME,

		isnull(c.AUTO_BRAND_NAME,'') as AUTO_BRAND_NAME,
		isnull(c.AUTO_VIN_CODE,'') as AUTO_VIN_CODE,
		isnull(convert(varchar(4),c.AUTO_PRODUCTION_YEAR),'') as AUTO_PRODUCTION_YEAR,
		c.AUTO_OWNERSHIP_CERTIFCATE_DATE,
		isnull(c.AUTO_OWNERSHIP_CERTIFCATE_NUMBER,'') as AUTO_OWNERSHIP_CERTIFCATE_NUMBER,

		isnull(Common.ahf_Unicode2ANSI(c.ESTATE_ADDRESS),'') as ESTATE_ADDRESS,
		isnull(c.ESTATE_RESIDENTIAL_AREA,0) as ESTATE_RESIDENTIAL_AREA,
		isnull(c.ESTATE_LAND_AREA,0) as ESTATE_LAND_AREA,

		isnull(c.PLEDGE_PRICE,0) as PLEDGE_PRICE,
		isnull(c.INSURANCE_COMPANY_CODE,'') as INSURANCE_COMPANY_CODE,
		isnull(c.PLEDGE_TYPE_ACRA,'') as PLEDGE_TYPE_ACRA,
		isnull(c.PLEDGE_TYPE_LR,'') as PLEDGE_TYPE_LR,

		isnull(c.DEVELOPER_CODE,'') as DEVELOPER_CODE,
		isnull(c.DEVELOPER_DELTA,0) as DEVELOPER_DELTA,
		isnull(c.DEVELOPER_AMOUNT,0) as DEVELOPER_AMOUNT,
		isnull(c.DEVELOPER_INTEREST,0) as DEVELOPER_INTEREST,
		COMPLETION_DATE,

		isnull(c.PREPAID_AMOUNT,0) as PREPAID_AMOUNT,
		isnull(c.LTV,0) as LTV,

		isnull(c.BRANCH_CODE,'') as BRANCH_CODE,
		isnull(c.USER_ID,'') as USER_ID
	from Common.COMPLETED_APPLICATION c
	join Common.APPLICATION a
		on c.APPLICATION_ID=a.ID
	left join Common.CUSTOMER_USER u
		on a.CUSTOMER_USER_ID=u.APPLICATION_USER_ID
	left join GL.AGREED_APPLICATION ag
		on a.ID=ag.APPLICATION_ID
	where c.APPLICATION_ID = @ID
GO
