insert into Common.SETTING (CODE, VALUE, DESCRIPTION)
values ('AGREEMENT_LIMIT', '300000', N'Համաձայնագրի սահմանաչափ')
GO



create or alter procedure Common.sp_GetMainApplication(@ID	uniqueidentifier)
AS
	select  c.FINAL_AMOUNT,
			c.INTEREST,
			rtrim(c.PERIOD_TYPE_CODE) as PERIOD_TYPE_CODE,
			c.REPAY_DAY,
			isnull(c.GOODS_RECEIVING_CODE,'1') as GOODS_RECEIVING_CODE,
			c.GOODS_DELIVERY_ADDRESS,
			c.FIRST_NAME_EN,
			c.LAST_NAME_EN,
			c.MOBILE_PHONE_1,
			c.MOBILE_PHONE_2,
			c.FIXED_PHONE,
			c.EMAIL,
			c.BIRTH_PLACE_CODE,
			c.CITIZENSHIP_CODE,
			c.REGISTRATION_COUNTRY_CODE,
			c.REGISTRATION_STATE_CODE,
			c.REGISTRATION_CITY_CODE,
			c.REGISTRATION_STREET,
			c.REGISTRATION_BUILDNUM,
			c.REGISTRATION_APARTMENT,
			c.CURRENT_COUNTRY_CODE,
			c.CURRENT_STATE_CODE,
			c.CURRENT_CITY_CODE,
			c.CURRENT_STREET,
			c.CURRENT_BUILDNUM,
			c.CURRENT_APARTMENT,
			c.COMMUNICATION_TYPE_CODE,
			c.COMPANY_NAME,
			c.COMPANY_PHONE,
			c.POSITION,
			c.MONTHLY_INCOME_CODE,
			c.WORKING_EXPERIENCE_CODE,
			c.FAMILY_STATUS_CODE,
			c.SHOP_CODE,
			c.PRODUCT_CATEGORY_CODE,
			c.PRODUCT_NUMBER,
			c.LOAN_TEMPLATE_CODE,
			c.OVERDRAFT_TEMPLATE_CODE,
			a.STATUS as STATUS_ID,
			a.LOAN_TYPE_ID,
			a.CURRENCY_CODE
	from Common.COMPLETED_APPLICATION c
		join Common.APPLICATION a
		on c.APPLICATION_ID = a.ID
	where c.APPLICATION_ID = @ID
GO
