insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('MC', '1', 'MCP1', 13, 6, 24, 'MOBILE PROMOTION 1', 0, 1.1)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('MC', '2', 'MCP2', 10, 6, 12, 'MOBILE PROMOTION 2', 0, 1.2)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('MC', '3', 'MCP3', 14, 24, 24, 'MOBILE PROMOTION 3', 0, 1.3)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('MC', '4', 'MCP4', 9, 6, 18, 'MOBILE PROMOTION 4', 0, 1.4)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('MC', '', 'MCO5', 16, 24, 48, 'MOBILE PROMOTION 5', 0, 1.5)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ARY', '1', 'ARY1', 15, 48, 48, 'ARAY PROMOTION 1', 0, 1.6)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ARY', '2', 'ARY2', 17, 12, 42, 'ARAY PROMOTION 2', 0, 1.7)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ARY', '3', 'ARY3', 19, 6, 12, 'ARAY PROMOTION 3', 0, 1.8)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ARY', '', 'ARY4', 17, 6, 60, 'ARAY PROMOTION 4', 0, 1.9)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ZG', '1', 'ZGZ1', 7, 12, 18, 'ZIGZAG PROMOTION 1', 0, 2.0)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ZG', '2', 'ZGZ2', 11, 6, 24, 'ZIGZAG PROMOTION 2', 0, 2.1)
GO
insert into IL.AGREEMENT_TEMPLATE (SHOP_CODE, PRODUCT_CATEGORY_CODE, TEMPLATE_CODE, INTEREST, TERM_FROM, TERM_TO, TEMPLATE_NAME, SERVICE_AMOUNT, SERVICE_INTEREST)
	values ('ZG', '3', 'ZGZ3', 13, 12, 42, 'ZIGZAG PROMOTION 3', 0, 2.2)
GO
