insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('01', 'AMD', 'TMP1', 'TEMPLATE NAME 1', 12, 48, 1)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'USD', 'TMP2', 'TEMPLATE NAME 2', 18, 48, 1)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'AMD', 'TMP3', 'TEMPLATE NAME 3', 30, 30, 1)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'EUR', 'TMP4', 'TEMPLATE NAME 4', 6, 18, 1)
GO

insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('01', 'AMD', 'TMP1', 'TEMPLATE NAME 1', 12, 48, 2)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'USD', 'TMP2', 'TEMPLATE NAME 2', 18, 48, 2)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'AMD', 'TMP3', 'TEMPLATE NAME 3', 30, 30, 2)
GO
insert into GL.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'EUR', 'TMP4', 'TEMPLATE NAME 4', 6, 18, 2)
GO
