insert into Common.LOAN_TYPE (CODE, NAME_AM, NAME_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, PLEDGE_TYPE, IS_STUDENT)
	values ('00', N'Ապառիկ', 'Installation', 1, 15, 0, 0, 0, 0, 0, 5, '', 0)
GO
insert into Common.LOAN_TYPE (CODE, NAME_AM, NAME_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, PLEDGE_TYPE, IS_STUDENT)
	values ('01', N'Սպառողական', 'Consumer', 1, 20, 0, 0, 0, 0, 1, 15, '', 0)
GO
insert into Common.LOAN_TYPE (CODE, NAME_AM, NAME_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, PLEDGE_TYPE, IS_STUDENT)
	values ('02', N'Օվերդրաֆտ', 'Overdraft', 1, 25, 1, 1, 1, 1, 1, 25, '', 0)
GO
insert into Common.LOAN_TYPE (CODE, NAME_AM, NAME_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, PLEDGE_TYPE, IS_STUDENT)
	values ('11', N'Ուսանողական', 'Student', 1, 20, 0, 0, 0, 0, 1, 15, '', 1)
GO
