INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('01', '1', 'AMD', '', 0, 5, 0, 10000)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('01', '9', 'AMD', '', 0, 7, 0, 10000)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '2', 'AMD', '', 0, 2, 0, 10000)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '3', 'AMD', '', 0, 4, 0, 10000)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '2', 'USD', '', 0, 4, 0, 100)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '3', 'USD', '', 0, 6, 0, 100)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '2', 'EUR', '', 0, 6, 0, 100)
GO
INSERT INTO Common.LOAN_SERVICE_CONDITION (LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE,AMOUNT,INTEREST,MIN_AMOUNT,MAX_AMOUNT)
	VALUES('02', '3', 'EUR', '', 0, 8, 0, 100)
GO
