insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ZG','1')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ZG','2')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ZG','3')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ZG','4')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ZG','9')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ARY','1')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('ARY','9')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('MC','2')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('MC','3')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('MC','9')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('VXB','5')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('VXB','9')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('MMB','6')
GO
insert into IL.SHOP_CATEGORY (SHOP_CODE, PRODUCT_CATEGORY_CODE) values ('MMB','9')
GO
