if exists (select * from sys.objects where name='ACRA_CLIENT_QUERY_RESULT_DETAILS' and type='U')
	drop table Common.ACRA_CLIENT_QUERY_RESULT_DETAILS
GO

CREATE TABLE Common.ACRA_CLIENT_QUERY_RESULT_DETAILS(
	RESULT_ID			uniqueidentifier	NOT NULL,
	STATUS				nvarchar(200)		NOT NULL,
	FROM_DATE			date				NOT NULL,
	TO_DATE				date				NOT NULL,
	TYPE				nvarchar(200)		NOT NULL,
	CUR					char(3)				NOT NULL,
	CONTRACT_AMOUNT		money				NOT NULL,
	DEBT				money				NOT NULL,
	PAST_DUE_DATE		date				NULL,
	RISK				nvarchar(200)		NOT NULL,
	CLASSIFICATION_DATE	date				NULL,
	INTEREST_RATE		money				NOT NULL,
	PLEDGE				nvarchar(1000)		NOT NULL,
	PLEDGE_AMOUNT		money				NOT NULL,
	OUTSTANDING_AMOUNT	money				NOT NULL,
	OUTSTANDING_PERCENT	money				NOT NULL,
	BANK_NAME			nvarchar(200)		NOT NULL,
	IS_GUARANTEE		bit					NOT NULL,
	DUE_DAYS_1			int					NOT NULL,
	DUE_DAYS_2			int					NOT NULL,
	DUE_DAYS_3			int					NOT NULL,
	DUE_DAYS_4			int					NOT NULL,
	LOAN_ID				varchar(20)			NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_CLIENT_QUERY_RESULT_DETAILS1 ON Common.ACRA_CLIENT_QUERY_RESULT_DETAILS (RESULT_ID)
GO

CREATE INDEX iACRA_CLIENT_QUERY_RESULT_DETAILS2 ON Common.ACRA_CLIENT_QUERY_RESULT_DETAILS (LOAN_ID)
GO
