if exists (select * from sys.objects where name='ACRA_CLIENT_QUERY_RESULT_QUERIES' and type='U')
	drop table Common.ACRA_CLIENT_QUERY_RESULT_QUERIES
GO

CREATE TABLE Common.ACRA_CLIENT_QUERY_RESULT_QUERIES(
	RESULT_ID	uniqueidentifier	NOT NULL,
	DATE		date				NOT NULL,
	BANK_NAME	nvarchar(100)		NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_CLIENT_QUERY_RESULT_QUERIES1 ON Common.ACRA_CLIENT_QUERY_RESULT_QUERIES (RESULT_ID,DATE)
GO
