if exists (select * from sys.objects where name='ACRA_CLIENT_QUERY_RESULT' and type='U')
	drop table Common.ACRA_CLIENT_QUERY_RESULT
GO

CREATE TABLE Common.ACRA_CLIENT_QUERY_RESULT(
	ID					uniqueidentifier	NOT NULL,
	SOCIAL_CARD_NUMBER	char(10)			NOT NULL,
	QUERY_DATE			datetime			NOT NULL default getdate(),
	USER_ID				char(4)				NOT NULL,
	IS_BLOCKED			bit					NOT NULL,
	FIRST_NAME			nvarchar(20)		NOT NULL,
	LAST_NAME			nvarchar(20)		NOT NULL,
	BIRTH_DATE			date				NULL,
	PASSPORT_NUMBER		char(9)				NULL,
	ID_CARD_NUMBER		char(9)				NULL,
	FICO_SCORE			char(3)				NOT NULL,
	RESPONSE_XML		nvarchar(max)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iACRA_CLIENT_QUERY_RESULT1 ON Common.ACRA_CLIENT_QUERY_RESULT (ID)
GO

CREATE UNIQUE INDEX iACRA_CLIENT_QUERY_RESULT2 ON Common.ACRA_CLIENT_QUERY_RESULT (SOCIAL_CARD_NUMBER,QUERY_DATE)
GO
