if exists (select * from sys.objects where name='APPLICATION' and type='U')
	drop table Common.APPLICATION
GO

CREATE TABLE Common.APPLICATION(
	CREATION_DATE				datetime			NOT NULL,
	SOURCE_ID					tinyint				NOT NULL,
	ID 							uniqueidentifier	NOT NULL,
	LOAN_TYPE_ID				char(2)				NOT NULL,
	STATUS						tinyint				NOT NULL,
	CUSTOMER_USER_ID			int					NULL,
	SHOP_USER_ID				int					NULL,
	INITIAL_AMOUNT				money				NULL,
	CURRENCY_CODE				char(3)				NULL,
	REFUSAL_REASON				nvarchar(100)		NULL,
	MANUAL_REASON				nvarchar(100)		NULL,
	IS_NEW_CARD					bit					NULL,
	GIVE_ACCOUNT				varchar(11)			NULL,
	GIVE_CARD					varchar(16)			NULL,

	FIRST_NAME					nvarchar(20)		NULL,
	LAST_NAME					nvarchar(20)		NULL,
	PATRONYMIC_NAME				nvarchar(20)		NULL,
	BIRTH_DATE					date				NULL,
	SOCIAL_CARD_NUMBER			char(10)			NULL,
	DOCUMENT_TYPE_CODE			char(1)				NULL,
	DOCUMENT_NUMBER				char(9)				NULL,
	DOCUMENT_GIVEN_BY			char(3)				NULL,
	DOCUMENT_GIVEN_DATE			date				NULL,
	DOCUMENT_EXPIRY_DATE		date				NULL,
	ORGANIZATION_ACTIVITY_CODE	char(2)				NULL,
	MOBILE_PHONE_1				varchar(20)			NULL,
	PRODUCT_CATEGORY_CODE		char(2)				NULL,
	LOAN_TEMPLATE_CODE			char(4)				NULL,
	PRODUCT_TOTAL_AMOUNT		money				NULL,
	IS_DATA_COMPLETE			bit					NULL,
	CLIENT_CODE					char(8)				NULL,
	ISN							int					NULL,
	HAS_BANK_CARD				bit					NULL,
	TO_BE_SYNCHRONIZED			bit					NOT NULL default 0,
	NORQ_TRY_COUNT				tinyint				NOT NULL default 0,
	ACRA_TRY_COUNT				tinyint				NOT NULL default 0,
	IS_REFINANCING				bit					NOT NULL default 0,
	REFINANCING_LOANS_AMOUNT	money				NULL,
	REFINANCING_LOANS_COUNT		int					NULL,
	IMPORT_ID					int					NULL,
	PARTNER_COMPANY_CODE		varchar(8)			NULL,
	PRINT_EXISTS				bit					NULL,
	IS_INSURED					bit					NULL,
	IS_REGISTERED				bit					NULL,
	IS_DISBURSED				bit					NULL,

	COBORROWER_SOCIAL_CARD_NUMBER	char(10)		NULL,
	COBORROWER_FIRST_NAME			nvarchar(20)	NULL,
	COBORROWER_LAST_NAME			nvarchar(20)	NULL,
	COBORROWER_BIRTH_DATE			date			NULL,
	COBORROWER_FIRST_NAME_EN		varchar(20)		NULL,
	COBORROWER_LAST_NAME_EN			varchar(20)		NULL,
	COBORROWER_MOBILE_PHONE			varchar(20)		NULL,
	COBORROWER_EMAIL				varchar(70)		NULL,
	COBORROWER_BIRTH_PLACE_CODE		char(2)			NULL,
	COBORROWER_CITIZENSHIP_CODE		char(2)			NULL,

	SKIP_OTI					bit					NULL,

	UNIVERSITY_CODE				char(2)			NULL,
	UNIVERSITY_FACULTY			nvarchar(50)	NULL,
	UNIVERSITY_YEAR				nvarchar(50)	NULL,

	CREATE_CLIENT_ONLY			bit				NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION1 ON Common.APPLICATION (ID)
GO

CREATE INDEX iAPPLICATION2 ON Common.APPLICATION (TO_BE_SYNCHRONIZED, CREATION_DATE)
GO

CREATE INDEX iAPPLICATION3 ON Common.APPLICATION (IMPORT_ID)
GO
