if exists (select * from sys.objects where name='COMPLETED_APPLICATION' and type='U')
	drop table Common.COMPLETED_APPLICATION
GO

CREATE TABLE Common.COMPLETED_APPLICATION (
	CREATION_DATE				datetime			NOT NULL default getdate(),
	APPLICATION_ID 				uniqueidentifier	NOT NULL,
	INTEREST					money				NULL,
	FINAL_AMOUNT				money				NULL,
	PERIOD_TYPE_CODE			char(3)				NULL,
	REPAY_DAY					tinyint				NULL,
	GOODS_RECEIVING_CODE		char(1)				NULL,
	GOODS_DELIVERY_ADDRESS		nvarchar(150)		NULL,

	FIRST_NAME_EN				varchar(20)			NULL,
	LAST_NAME_EN				varchar(20)			NULL,
	MOBILE_PHONE_1				varchar(20)			NULL,
	MOBILE_PHONE_2				varchar(20)			NULL,
	FIXED_PHONE					varchar(20)			NULL,
	EMAIL						varchar(70)			NULL,
	BIRTH_PLACE_CODE			char(2)				NULL,
	CITIZENSHIP_CODE			char(2)				NULL,
	REGISTRATION_COUNTRY_CODE	char(2)				NULL,
	REGISTRATION_STATE_CODE		char(3)				NULL,
	REGISTRATION_CITY_CODE		char(9)				NULL,
	REGISTRATION_STREET			nvarchar(150)		NULL,
	REGISTRATION_BUILDNUM		nvarchar(30)		NULL,
	REGISTRATION_APARTMENT		nvarchar(30)		NULL,
	CURRENT_COUNTRY_CODE		char(2)				NULL,
	CURRENT_STATE_CODE			char(3)				NULL,
	CURRENT_CITY_CODE			char(9)				NULL,
	CURRENT_STREET				nvarchar(150)		NULL,
	CURRENT_BUILDNUM			nvarchar(30)		NULL,
	CURRENT_APARTMENT			nvarchar(30)		NULL,
	COMMUNICATION_TYPE_CODE		char(1)				NULL,
	COMPANY_NAME				nvarchar(40)		NULL,
	COMPANY_PHONE				varchar(20)			NULL,
	POSITION					nvarchar(50)		NULL,
	MONTHLY_INCOME_CODE			char(1)				NULL,
	WORKING_EXPERIENCE_CODE		char(1)				NULL,
	FAMILY_STATUS_CODE			char(1)				NULL,
	SHOP_CODE					char(4)				NULL,
	PRODUCT_CATEGORY_CODE		char(2)				NULL,
	PRODUCT_NUMBER				varchar(20)			NULL,
	LOAN_TEMPLATE_CODE			char(4)				NULL,
	OVERDRAFT_TEMPLATE_CODE		char(4)				NULL,
	SHOP_SEQUENCE_NUMBER		varchar(20)			NULL,
	IS_CURRENT_ADDRESS_SAME		bit					NULL,

	AUTO_BRAND_NAME						nvarchar(100)		NULL,
	AUTO_VIN_CODE						varchar(17)			NULL,
	AUTO_PRODUCTION_YEAR				smallint			NULL,
	AUTO_OWNERSHIP_CERTIFCATE_DATE		date				NULL,
	AUTO_OWNERSHIP_CERTIFCATE_NUMBER	nvarchar(20)		NULL,

	ESTATE_ADDRESS						nvarchar(140)		NULL,
	ESTATE_RESIDENTIAL_AREA				money				NULL,
	ESTATE_LAND_AREA					money				NULL,

	PLEDGE_PRICE				money				NULL,
	INSURANCE_COMPANY_CODE		char(3)				NULL,
	PLEDGE_TYPE_ACRA			char(2)				NULL,
	PLEDGE_TYPE_LR				char(2)				NULL,

	DEVELOPER_CODE				varchar(8)			NULL,
	DEVELOPER_DELTA				bit					NULL,
	DEVELOPER_AMOUNT			money				NULL,
	DEVELOPER_INTEREST			money				NULL,
	COMPLETION_DATE				date				NULL,

	PREPAID_AMOUNT				money				NULL,
	LTV							money				NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iCOMPLETED_APPLICATION1 ON Common.COMPLETED_APPLICATION(APPLICATION_ID)
GO
