if exists (select * from sys.objects where name='LOAN_SERVICE_CONDITION' and type='U')
	drop table Common.LOAN_SERVICE_CONDITION
GO

CREATE TABLE Common.LOAN_SERVICE_CONDITION (
	LOAN_TYPE_CODE			char(2)	NOT NULL,
	SERVICE_TYPE_CODE		char(1)	NOT NULL,
	CURRENCY				char(3)	NOT NULL,
	CREDIT_CARD_TYPE_CODE	char(3)	NULL,
	AMOUNT					money	NOT NULL,
	INTEREST				money	NOT NULL,
	MIN_AMOUNT				money	NULL,
	MAX_AMOUNT				money	NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iLOAN_SERVICE_CONDITION1 ON Common.LOAN_SERVICE_CONDITION(LOAN_TYPE_CODE,SERVICE_TYPE_CODE,CURRENCY,CREDIT_CARD_TYPE_CODE)
GO
