create or alter procedure Common.sp_GetApplicationForOnboarding(@ID	uniqueidentifier)
AS
	select au.FIRST_NAME as FIRST_NAME_EN
		,au.LAST_NAME as LAST_NAME_EN
		,au.EMAIL
		,au.LOGIN as PHONE
		,n.FIRST_NAME as FIRST_NAME_AM
		,n.LAST_NAME as LAST_NAME_AM
		,n.PATRONYMIC_NAME as PATRONYMIC_NAME_AM
		,n.BIRTH_DATE
		,n.GENDER
		,n.DISTRICT
		,n.COMMUNITY
		,n.STREET
		,n.BUILDING
		,n.APARTMENT
		,n.FEE as SALARY
		,n.PASSPORT_NUMBER as NON_BIOMETRIC_PASSPORT_NUMBER
		,n.PASSPORT_DATE as NON_BIOMETRIC_PASSPORT_ISSUE_DATE
		,n.PASSPORT_EXPIRY_DATE as NON_BIOMETRIC_PASSPORT_EXPIRY_DATE
		,n.PASSPORT_BY as NON_BIOMETRIC_PASSPORT_ISSUED_BY
		,n.BIOMETRIC_PASSPORT_NUMBER
		,n.BIOMETRIC_PASSPORT_ISSUE_DATE
		,n.BIOMETRIC_PASSPORT_EXPIRY_DATE
		,n.BIOMETRIC_PASSPORT_ISSUED_BY
		,n.ID_CARD_NUMBER
		,n.ID_CARD_ISSUE_DATE
		,n.ID_CARD_EXPIRY_DATE
		,n.ID_CARD_ISSUED_BY
		,n.SOCIAL_CARD_NUMBER
		,a.DOCUMENT_TYPE_CODE
		,a.DOCUMENT_NUMBER
		,isnull(cu.IS_STUDENT,0) as IS_STUDENT
	from Common.APPLICATION a with (NOLOCK)
	join Common.NORQ_QUERY_RESULT n with (NOLOCK)
		on a.ID=n.APPLICATION_ID
	join Common.APPLICATION_USER au with (NOLOCK)
		on a.CUSTOMER_USER_ID=au.ID
	join Common.CUSTOMER_USER cu with (NOLOCK)
		on cu.APPLICATION_USER_ID=au.ID
	where a.ID=@ID
GO
