CREATE OR ALTER PROCEDURE Common.sp_GetACRACoborrowerQueries(@APPLICATION_ID	uniqueidentifier)
AS
	select DATE,Common.ahf_Unicode2ANSI(BANK_NAME) as BANK_NAME
	from Common.ACRA_COBORROWER_QUERY_RESULT_QUERIES
	where APPLICATION_ID=@APPLICATION_ID
	order by DATE
GO
