CREATE OR ALTER PROCEDURE Common.sp_GetACRACoborrowerDetails(@APPLICATION_ID	uniqueidentifier)
AS
	select Common.ahf_Unicode2ANSI(STATUS) as STATUS,FROM_DATE,TO_DATE,Common.ahf_Unicode2ANSI(TYPE) as TYPE,
		case CUR when 'RUR' then 'RUB' else CUR end as CUR,
		CONTRACT_AMOUNT,DEBT,PAST_DUE_DATE,Common.ahf_Unicode2ANSI(RISK) as RISK,CLASSIFICATION_DATE,
		INTEREST_RATE,Common.ahf_Unicode2ANSI(PLEDGE) as PLEDGE_SUBJECT,PLEDGE_AMOUNT,IS_GUARANTEE,OUTSTANDING_AMOUNT,OUTSTANDING_PERCENT,Common.ahf_Unicode2ANSI(BANK_NAME) as BANK_NAME,
		DUE_DAYS_1,DUE_DAYS_2,DUE_DAYS_3,DUE_DAYS_4,LOAN_ID
	from Common.ACRA_COBORROWER_QUERY_RESULT_DETAILS
	where APPLICATION_ID=@APPLICATION_ID
	order by IS_GUARANTEE,STATUS
GO
