CREATE OR ALTER PROCEDURE Common.sp_GetApplicationAfterNORQ(@ID	uniqueidentifier)
AS
	select isnull(a.ISN,-1) as ISN,a.LOAN_TYPE_ID,a.INITIAL_AMOUNT,a.CURRENCY_CODE
		,Common.ahf_Unicode2ANSI(a.FIRST_NAME) as FIRST_NAME,Common.ahf_Unicode2ANSI(a.LAST_NAME) as LAST_NAME,Common.ahf_Unicode2ANSI(a.PATRONYMIC_NAME) as PATRONYMIC_NAME,a.BIRTH_DATE
		,a.SOCIAL_CARD_NUMBER,a.DOCUMENT_TYPE_CODE,a.DOCUMENT_NUMBER,a.DOCUMENT_GIVEN_BY,a.DOCUMENT_GIVEN_DATE,a.DOCUMENT_EXPIRY_DATE,isnull(a.ORGANIZATION_ACTIVITY_CODE,'') as ORGANIZATION_ACTIVITY_CODE
		,Common.f_GetAge(n.BIRTH_DATE) as AGE,Common.ahf_Unicode2ANSI(n.FIRST_NAME) as NORQ_FIRST_NAME,Common.ahf_Unicode2ANSI(n.LAST_NAME) as NORQ_LAST_NAME,Common.ahf_Unicode2ANSI(n.PATRONYMIC_NAME) as NORQ_PATRONYMIC_NAME,n.BIRTH_DATE as NORQ_BIRTH_DATE,n.GENDER
		,Common.ahf_Unicode2ANSI(n.DISTRICT) as DISTRICT,Common.ahf_Unicode2ANSI(n.COMMUNITY) as COMMUNITY,Common.ahf_Unicode2ANSI(n.STREET) as STREET,Common.ahf_Unicode2ANSI(n.BUILDING) as BUILDING,Common.ahf_Unicode2ANSI(n.APARTMENT) as APARTMENT
		,isnull(n.PASSPORT_NUMBER,'') as PASSPORT_NUMBER,n.PASSPORT_DATE,n.PASSPORT_EXPIRY_DATE,n.PASSPORT_BY
		,isnull(n.BIOMETRIC_PASSPORT_NUMBER,'') as BIOMETRIC_PASSPORT_NUMBER,n.BIOMETRIC_PASSPORT_ISSUE_DATE,n.BIOMETRIC_PASSPORT_EXPIRY_DATE,n.BIOMETRIC_PASSPORT_ISSUED_BY
		,isnull(n.ID_CARD_NUMBER,'') as ID_CARD_NUMBER,n.ID_CARD_ISSUE_DATE,n.ID_CARD_EXPIRY_DATE,n.ID_CARD_ISSUED_BY
		,n.SOCIAL_CARD_NUMBER as NORQ_SOCIAL_CARD_NUMBER,n.FEE,n.SOCIAL_PAYMENT
		,coalesce(a.MOBILE_PHONE_1,au.LOGIN,'') as MOBILE_PHONE_1,isnull(au.EMAIL,'') as EMAIL,isnull(cu.FIRST_NAME_EN,'') as FIRST_NAME_EN,isnull(cu.LAST_NAME_EN,'') as LAST_NAME_EN
		,isnull(a.PRODUCT_CATEGORY_CODE,'') as PRODUCT_CATEGORY_CODE,isnull(a.LOAN_TEMPLATE_CODE,'') as LOAN_TEMPLATE_CODE
		,a.NORQ_TRY_COUNT,a.ACRA_TRY_COUNT,a.IS_REFINANCING
		,a.COBORROWER_SOCIAL_CARD_NUMBER,Common.ahf_Unicode2ANSI(isnull(a.COBORROWER_FIRST_NAME,'')) as COBORROWER_FIRST_NAME,Common.ahf_Unicode2ANSI(isnull(a.COBORROWER_LAST_NAME,'')) as COBORROWER_LAST_NAME
		,a.COBORROWER_BIRTH_DATE,a.COBORROWER_FIRST_NAME_EN,a.COBORROWER_LAST_NAME_EN,a.COBORROWER_MOBILE_PHONE,a.COBORROWER_EMAIL,a.COBORROWER_BIRTH_PLACE_CODE,a.COBORROWER_CITIZENSHIP_CODE
		,isnull(a.SKIP_OTI,0) as SKIP_OTI
		,a.UNIVERSITY_CODE,a.UNIVERSITY_FACULTY,a.UNIVERSITY_YEAR
		,Common.f_GetAge(nc.BIRTH_DATE) as COBORROWER_AGE,Common.ahf_Unicode2ANSI(nc.FIRST_NAME) as NORQ_COBORROWER_FIRST_NAME,Common.ahf_Unicode2ANSI(nc.LAST_NAME) as NORQ_COBORROWER_LAST_NAME,Common.ahf_Unicode2ANSI(nc.PATRONYMIC_NAME) as NORQ_COBORROWER_PATRONYMIC_NAME,nc.BIRTH_DATE as NORQ_COBORROWER_BIRTH_DATE,nc.GENDER as COBORROWER_GENDER
		,Common.ahf_Unicode2ANSI(nc.DISTRICT) as COBORROWER_DISTRICT,Common.ahf_Unicode2ANSI(nc.COMMUNITY) as COBORROWER_COMMUNITY,Common.ahf_Unicode2ANSI(nc.STREET) as COBORROWER_STREET,Common.ahf_Unicode2ANSI(nc.BUILDING) as COBORROWER_BUILDING,Common.ahf_Unicode2ANSI(nc.APARTMENT) as COBORROWER_APARTMENT
		,isnull(nc.PASSPORT_NUMBER,'') as COBORROWER_PASSPORT_NUMBER,nc.PASSPORT_DATE as COBORROWER_PASSPORT_DATE,nc.PASSPORT_EXPIRY_DATE as COBORROWER_PASSPORT_EXPIRY_DATE,nc.PASSPORT_BY as COBORROWER_PASSPORT_BY
		,isnull(nc.BIOMETRIC_PASSPORT_NUMBER,'') as COBORROWER_BIOMETRIC_PASSPORT_NUMBER,nc.BIOMETRIC_PASSPORT_ISSUE_DATE as COBORROWER_BIOMETRIC_PASSPORT_ISSUE_DATE,nc.BIOMETRIC_PASSPORT_EXPIRY_DATE as COBORROWER_BIOMETRIC_PASSPORT_EXPIRY_DATE,nc.BIOMETRIC_PASSPORT_ISSUED_BY as COBORROWER_BIOMETRIC_PASSPORT_ISSUED_BY
		,isnull(nc.ID_CARD_NUMBER,'') as COBORROWER_ID_CARD_NUMBER,nc.ID_CARD_ISSUE_DATE as COBORROWER_ID_CARD_ISSUE_DATE,nc.ID_CARD_EXPIRY_DATE as COBORROWER_ID_CARD_EXPIRY_DATE,nc.ID_CARD_ISSUED_BY as COBORROWER_ID_CARD_ISSUED_BY
		,nc.SOCIAL_CARD_NUMBER as NORQ_COBORROWER_SOCIAL_CARD_NUMBER,nc.FEE as COBORROWER_FEE,nc.SOCIAL_PAYMENT as COBORROWER_SOCIAL_PAYMENT
	from Common.APPLICATION a with (NOLOCK)
	join Common.NORQ_QUERY_RESULT n with (NOLOCK)
		on n.APPLICATION_ID=a.ID
	left join Common.NORQ_COBORROWER_QUERY_RESULT nc with (NOLOCK)
		on nc.APPLICATION_ID=a.ID
	left join Common.CUSTOMER_USER cu with (NOLOCK)
		on cu.APPLICATION_USER_ID=a.CUSTOMER_USER_ID
	left join Common.APPLICATION_USER au with (NOLOCK)
		on au.ID=cu.APPLICATION_USER_ID
	where a.ID=@ID
GO
