CREATE OR ALTER PROCEDURE Common.sp_GetApplicationBeforeNORQ(@ID	uniqueidentifier)
AS
	select isnull(a.ISN,-1) as ISN,a.LOAN_TYPE_ID,a.INITIAL_AMOUNT,a.CURRENCY_CODE
		,Common.ahf_Unicode2ANSI(a.FIRST_NAME) as FIRST_NAME,Common.ahf_Unicode2ANSI(a.LAST_NAME) as LAST_NAME,Common.ahf_Unicode2ANSI(a.PATRONYMIC_NAME) as PATRONYMIC_NAME,a.BIRTH_DATE
		,a.SOCIAL_CARD_NUMBER,a.DOCUMENT_TYPE_CODE,a.DOCUMENT_NUMBER,a.DOCUMENT_GIVEN_BY,a.DOCUMENT_GIVEN_DATE,a.DOCUMENT_EXPIRY_DATE,isnull(a.ORGANIZATION_ACTIVITY_CODE,'') as ORGANIZATION_ACTIVITY_CODE
		,coalesce(a.MOBILE_PHONE_1,au.LOGIN,'') as MOBILE_PHONE_1,isnull(au.EMAIL,'') as EMAIL,isnull(cu.FIRST_NAME_EN,'') as FIRST_NAME_EN,isnull(cu.LAST_NAME_EN,'') as LAST_NAME_EN
		,isnull(a.PRODUCT_CATEGORY_CODE,'') as PRODUCT_CATEGORY_CODE,isnull(a.LOAN_TEMPLATE_CODE,'') as LOAN_TEMPLATE_CODE
		,a.NORQ_TRY_COUNT,a.IS_REFINANCING
		,a.COBORROWER_SOCIAL_CARD_NUMBER,Common.ahf_Unicode2ANSI(isnull(a.COBORROWER_FIRST_NAME,'')) as COBORROWER_FIRST_NAME,Common.ahf_Unicode2ANSI(isnull(a.COBORROWER_LAST_NAME,'')) as COBORROWER_LAST_NAME
		,a.COBORROWER_BIRTH_DATE,a.COBORROWER_FIRST_NAME_EN,a.COBORROWER_LAST_NAME_EN,a.COBORROWER_MOBILE_PHONE,a.COBORROWER_EMAIL,a.COBORROWER_BIRTH_PLACE_CODE,a.COBORROWER_CITIZENSHIP_CODE
		,isnull(a.SKIP_OTI,0) as SKIP_OTI
		,a.UNIVERSITY_CODE,a.UNIVERSITY_FACULTY,a.UNIVERSITY_YEAR
		from Common.APPLICATION a with (NOLOCK)
		left join Common.CUSTOMER_USER cu with (NOLOCK)
			on cu.APPLICATION_USER_ID=a.CUSTOMER_USER_ID
		left join Common.APPLICATION_USER au with (NOLOCK)
			on au.ID=cu.APPLICATION_USER_ID
		where a.ID=@ID
GO
