create or alter procedure Common.sp_SaveNORQClientQueryResult(@SOCIAL_CARD_NUMBER					char(10),
													 @USER_ID								char(4),
													 @FIRST_NAME							nvarchar(20),
													 @LAST_NAME								nvarchar(20),
													 @PATRONYMIC_NAME						nvarchar(20) = NULL,
													 @BIRTH_DATE							date = NULL,
													 @IS_DEAD								bit = NULL,
													 @GENDER								bit = NULL,
													 @DISTRICT								nvarchar(20) = NULL,
													 @COMMUNITY								nvarchar(40) = NULL,
													 @STREET								nvarchar(100) = NULL,
													 @BUILDING								nvarchar(40) = NULL,
													 @APARTMENT								nvarchar(40) = NULL,
													 @FEE									money = NULL,
													 @NON_BIOMETRIC_PASSPORT_NUMBER			char(9) = NULL,
													 @NON_BIOMETRIC_PASSPORT_ISSUE_DATE		date = NULL,
													 @NON_BIOMETRIC_PASSPORT_EXPIRY_DATE	date = NULL,
													 @NON_BIOMETRIC_PASSPORT_ISSUED_BY		char(3) = NULL,
													 @BIOMETRIC_PASSPORT_NUMBER				char(9) = NULL,
													 @BIOMETRIC_PASSPORT_ISSUE_DATE			date = NULL,
													 @BIOMETRIC_PASSPORT_EXPIRY_DATE		date = NULL,
													 @BIOMETRIC_PASSPORT_ISSUED_BY			char(3) = NULL,
													 @ID_CARD_NUMBER						char(9) = NULL,
													 @ID_CARD_ISSUE_DATE					date = NULL,
													 @ID_CARD_EXPIRY_DATE					date = NULL,
													 @ID_CARD_ISSUED_BY						char(3) = NULL,
													 @ORGANIZATION_NAME						nvarchar(100) = NULL,
													 @REGISTRATION_CODE						nvarchar(20) = NULL,
													 @TAX_CODE								varchar(20) = NULL,
													 @ORGANIZATION_ADDRESS					nvarchar(100) = NULL,
													 @POSITION								nvarchar(400) = NULL,
													 @AGREEMENT_START_DATE					date = NULL,
													 @AGREEMENT_END_DATE					date = NULL,
													 @RESPONSE_XML							nvarchar(max))
AS
	BEGIN TRANSACTION
	BEGIN TRY
		declare @CURRENT_DATE date=getdate()
		delete from Common.NORQ_CLIENT_QUERY_RESULT
		where SOCIAL_CARD_NUMBER=@SOCIAL_CARD_NUMBER
			and convert(date,QUERY_DATE)=@CURRENT_DATE

		insert into Common.NORQ_CLIENT_QUERY_RESULT
			(SOCIAL_CARD_NUMBER,USER_ID,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,BIRTH_DATE,IS_DEAD,GENDER,
			DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,
			NON_BIOMETRIC_PASSPORT_NUMBER,NON_BIOMETRIC_PASSPORT_ISSUE_DATE,NON_BIOMETRIC_PASSPORT_EXPIRY_DATE,NON_BIOMETRIC_PASSPORT_ISSUED_BY,
			BIOMETRIC_PASSPORT_NUMBER,BIOMETRIC_PASSPORT_ISSUE_DATE,BIOMETRIC_PASSPORT_EXPIRY_DATE,BIOMETRIC_PASSPORT_ISSUED_BY,
			ID_CARD_NUMBER,ID_CARD_ISSUE_DATE,ID_CARD_EXPIRY_DATE,ID_CARD_ISSUED_BY,
			ORGANIZATION_NAME,REGISTRATION_CODE,TAX_CODE,ORGANIZATION_ADDRESS,POSITION,AGREEMENT_START_DATE,AGREEMENT_END_DATE,FEE,RESPONSE_XML)
		values
			(@SOCIAL_CARD_NUMBER,@USER_ID,@FIRST_NAME,@LAST_NAME,@PATRONYMIC_NAME,@BIRTH_DATE,@IS_DEAD,@GENDER,
			@DISTRICT,@COMMUNITY,@STREET,@BUILDING,@APARTMENT,
			@NON_BIOMETRIC_PASSPORT_NUMBER,@NON_BIOMETRIC_PASSPORT_ISSUE_DATE,@NON_BIOMETRIC_PASSPORT_EXPIRY_DATE,@NON_BIOMETRIC_PASSPORT_ISSUED_BY,
			@BIOMETRIC_PASSPORT_NUMBER,@BIOMETRIC_PASSPORT_ISSUE_DATE,@BIOMETRIC_PASSPORT_EXPIRY_DATE,@BIOMETRIC_PASSPORT_ISSUED_BY,
			@ID_CARD_NUMBER,@ID_CARD_ISSUE_DATE,@ID_CARD_EXPIRY_DATE,@ID_CARD_ISSUED_BY,
			@ORGANIZATION_NAME,@REGISTRATION_CODE,@TAX_CODE,@ORGANIZATION_ADDRESS,@POSITION,@AGREEMENT_START_DATE,@AGREEMENT_END_DATE,@FEE,@RESPONSE_XML)
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage varchar(4000)
		set @ErrorMessage = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
		RETURN
	END CATCH
	COMMIT TRANSACTION
GO
