create or alter procedure Common.sp_SaveNORQQueryResult(
	@APPLICATION_ID					uniqueidentifier,
	@FIRST_NAME						nvarchar(20),
	@LAST_NAME						nvarchar(20),
	@PATRONYMIC_NAME				nvarchar(20),
	@BIRTH_DATE						date,
	@GENDER							bit,
	@DISTRICT						nvarchar(20),
	@COMMUNITY						nvarchar(40),
	@STREET							nvarchar(100),
	@BUILDING						nvarchar(40),
	@APARTMENT						nvarchar(40),
	@FEE							money,
	@PASSPORT_NUMBER				char(9) = NULL,
	@PASSPORT_DATE					date = NULL,
	@PASSPORT_EXPIRY_DATE			date = NULL,
	@PASSPORT_BY					char(3) = NULL,
	@BIOMETRIC_PASSPORT_NUMBER		char(9) = NULL,
	@BIOMETRIC_PASSPORT_ISSUE_DATE	date = NULL,
	@BIOMETRIC_PASSPORT_EXPIRY_DATE	date = NULL,
	@BIOMETRIC_PASSPORT_ISSUED_BY	char(3) = NULL,
	@ID_CARD_NUMBER					char(9) = NULL,
	@ID_CARD_ISSUE_DATE				date = NULL,
	@ID_CARD_EXPIRY_DATE			date = NULL,
	@ID_CARD_ISSUED_BY				char(3) = NULL,
	@SOCIAL_CARD_NUMBER				char(10),
	@SOCIAL_PAYMENT					money,
	@RESPONSE_XML					nvarchar(max),
	@WORK_DATA						Common.NORQQueryResultWork	readonly,

	@COBORROWER_FIRST_NAME						nvarchar(20) = NULL,
	@COBORROWER_LAST_NAME						nvarchar(20) = NULL,
	@COBORROWER_PATRONYMIC_NAME					nvarchar(20) = NULL,
	@COBORROWER_BIRTH_DATE						date = NULL,
	@COBORROWER_GENDER							bit = NULL,
	@COBORROWER_DISTRICT						nvarchar(20) = NULL,
	@COBORROWER_COMMUNITY						nvarchar(40) = NULL,
	@COBORROWER_STREET							nvarchar(100) = NULL,
	@COBORROWER_BUILDING						nvarchar(40) = NULL,
	@COBORROWER_APARTMENT						nvarchar(40) = NULL,
	@COBORROWER_FEE								money = NULL,
	@COBORROWER_PASSPORT_NUMBER					char(9) = NULL,
	@COBORROWER_PASSPORT_DATE					date = NULL,
	@COBORROWER_PASSPORT_EXPIRY_DATE			date = NULL,
	@COBORROWER_PASSPORT_BY						char(3) = NULL,
	@COBORROWER_BIOMETRIC_PASSPORT_NUMBER		char(9) = NULL,
	@COBORROWER_BIOMETRIC_PASSPORT_ISSUE_DATE	date = NULL,
	@COBORROWER_BIOMETRIC_PASSPORT_EXPIRY_DATE	date = NULL,
	@COBORROWER_BIOMETRIC_PASSPORT_ISSUED_BY	char(3) = NULL,
	@COBORROWER_ID_CARD_NUMBER					char(9) = NULL,
	@COBORROWER_ID_CARD_ISSUE_DATE				date = NULL,
	@COBORROWER_ID_CARD_EXPIRY_DATE				date = NULL,
	@COBORROWER_ID_CARD_ISSUED_BY				char(3) = NULL,
	@COBORROWER_SOCIAL_CARD_NUMBER				char(10) = NULL,
	@COBORROWER_SOCIAL_PAYMENT					money = NULL,
	@COBORROWER_RESPONSE_XML					nvarchar(max) = NULL,
	@COBORROWER_WORK_DATA						Common.NORQQueryResultWork	readonly
)
AS
	BEGIN TRANSACTION
	BEGIN TRY
		declare @CURRENT_STATUS tinyint,@DOCUMENT_NUMBER char(9)
			,@DOCUMENT_GIVEN_BY char(3),@DOCUMENT_GIVEN_DATE date,@DOCUMENT_EXPIRY_DATE date

		select @CURRENT_STATUS = STATUS
			,@DOCUMENT_NUMBER = DOCUMENT_NUMBER
		from Common.APPLICATION with (updlock)
		where ID = @APPLICATION_ID

		if @DOCUMENT_NUMBER=@PASSPORT_NUMBER
		begin
			set @DOCUMENT_GIVEN_BY = @PASSPORT_BY
			set @DOCUMENT_GIVEN_DATE = @PASSPORT_DATE
			set @DOCUMENT_EXPIRY_DATE = @PASSPORT_EXPIRY_DATE
		end
		else if @DOCUMENT_NUMBER=@BIOMETRIC_PASSPORT_NUMBER
		begin
			set @DOCUMENT_GIVEN_BY = @BIOMETRIC_PASSPORT_ISSUED_BY
			set @DOCUMENT_GIVEN_DATE = @BIOMETRIC_PASSPORT_ISSUE_DATE
			set @DOCUMENT_EXPIRY_DATE = @BIOMETRIC_PASSPORT_EXPIRY_DATE
		end
		else if @DOCUMENT_NUMBER=@ID_CARD_NUMBER
		begin
			set @DOCUMENT_GIVEN_BY = @ID_CARD_ISSUED_BY
			set @DOCUMENT_GIVEN_DATE = @ID_CARD_ISSUE_DATE
			set @DOCUMENT_EXPIRY_DATE = @ID_CARD_EXPIRY_DATE
		end
		else
		begin
			execute Common.sp_AutomaticallyRefuseApplication @APPLICATION_ID,N'Սխալ փաստաթղթի տվյալներ'
			COMMIT TRANSACTION
			RETURN
		end

		if @CURRENT_STATUS <> 1
			RAISERROR (N'Հայտի կարգավիճակն արդեն փոփոխվել է', 17, 1)

		declare @CurrentDate date = getdate()

		insert into Common.NORQ_QUERY_RESULT
			(APPLICATION_ID,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,BIRTH_DATE,GENDER,
			DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,
			PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,
			BIOMETRIC_PASSPORT_NUMBER,BIOMETRIC_PASSPORT_ISSUE_DATE,BIOMETRIC_PASSPORT_EXPIRY_DATE,BIOMETRIC_PASSPORT_ISSUED_BY,
			ID_CARD_NUMBER,ID_CARD_ISSUE_DATE,ID_CARD_EXPIRY_DATE,ID_CARD_ISSUED_BY,
			SOCIAL_CARD_NUMBER,FEE,SOCIAL_PAYMENT,RESPONSE_XML)
		values
			(@APPLICATION_ID,@FIRST_NAME,@LAST_NAME,@PATRONYMIC_NAME,@BIRTH_DATE,@GENDER,
			@DISTRICT,@COMMUNITY,@STREET,@BUILDING,@APARTMENT,
			isnull(@PASSPORT_NUMBER,''),isnull(@PASSPORT_DATE,@CurrentDate),isnull(@PASSPORT_EXPIRY_DATE,@CurrentDate),isnull(@PASSPORT_BY,''),
			isnull(@BIOMETRIC_PASSPORT_NUMBER,''),isnull(@BIOMETRIC_PASSPORT_ISSUE_DATE,@CurrentDate),isnull(@BIOMETRIC_PASSPORT_EXPIRY_DATE,@CurrentDate),isnull(@BIOMETRIC_PASSPORT_ISSUED_BY,''),
			isnull(@ID_CARD_NUMBER,''),isnull(@ID_CARD_ISSUE_DATE,@CurrentDate),isnull(@ID_CARD_EXPIRY_DATE,@CurrentDate),isnull(@ID_CARD_ISSUED_BY,''),
			@SOCIAL_CARD_NUMBER,@FEE,@SOCIAL_PAYMENT,@RESPONSE_XML)

		delete from Common.NORQ_QUERY_RESULT_WORK where APPLICATION_ID=@APPLICATION_ID
		insert into Common.NORQ_QUERY_RESULT_WORK
			(APPLICATION_ID,ORGANIZATION_NAME,TAX_ID_NUMBER,ADDRESS,FROM_DATE,TO_DATE,SALARY,SOCIAL_PAYMENT,POSITION)
		select @APPLICATION_ID,ORGANIZATION_NAME,TAX_ID_NUMBER,ADDRESS,FROM_DATE,TO_DATE,SALARY,SOCIAL_PAYMENT,POSITION
			from @WORK_DATA

		if rtrim(isnull(@COBORROWER_RESPONSE_XML,''))<>''
		begin
			insert into Common.NORQ_COBORROWER_QUERY_RESULT
				(APPLICATION_ID,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,BIRTH_DATE,GENDER,
				DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,
				PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,
				BIOMETRIC_PASSPORT_NUMBER,BIOMETRIC_PASSPORT_ISSUE_DATE,BIOMETRIC_PASSPORT_EXPIRY_DATE,BIOMETRIC_PASSPORT_ISSUED_BY,
				ID_CARD_NUMBER,ID_CARD_ISSUE_DATE,ID_CARD_EXPIRY_DATE,ID_CARD_ISSUED_BY,
				SOCIAL_CARD_NUMBER,FEE,SOCIAL_PAYMENT,RESPONSE_XML)
			values
				(@APPLICATION_ID,@COBORROWER_FIRST_NAME,@COBORROWER_LAST_NAME,@COBORROWER_PATRONYMIC_NAME,@COBORROWER_BIRTH_DATE,@COBORROWER_GENDER,
				@COBORROWER_DISTRICT,@COBORROWER_COMMUNITY,@COBORROWER_STREET,@COBORROWER_BUILDING,@COBORROWER_APARTMENT,
				isnull(@COBORROWER_PASSPORT_NUMBER,''),isnull(@COBORROWER_PASSPORT_DATE,@CurrentDate),isnull(@COBORROWER_PASSPORT_EXPIRY_DATE,@CurrentDate),isnull(@COBORROWER_PASSPORT_BY,''),
				isnull(@COBORROWER_BIOMETRIC_PASSPORT_NUMBER,''),isnull(@COBORROWER_BIOMETRIC_PASSPORT_ISSUE_DATE,@CurrentDate),isnull(@COBORROWER_BIOMETRIC_PASSPORT_EXPIRY_DATE,@CurrentDate),isnull(@COBORROWER_BIOMETRIC_PASSPORT_ISSUED_BY,''),
				isnull(@COBORROWER_ID_CARD_NUMBER,''),isnull(@COBORROWER_ID_CARD_ISSUE_DATE,@CurrentDate),isnull(@COBORROWER_ID_CARD_EXPIRY_DATE,@CurrentDate),isnull(@COBORROWER_ID_CARD_ISSUED_BY,''),
				@COBORROWER_SOCIAL_CARD_NUMBER,@COBORROWER_FEE,@COBORROWER_SOCIAL_PAYMENT,@COBORROWER_RESPONSE_XML)

			delete from Common.NORQ_COBORROWER_QUERY_RESULT_WORK where APPLICATION_ID=@APPLICATION_ID
			insert into Common.NORQ_COBORROWER_QUERY_RESULT_WORK
				(APPLICATION_ID,ORGANIZATION_NAME,TAX_ID_NUMBER,ADDRESS,FROM_DATE,TO_DATE,SALARY,SOCIAL_PAYMENT,POSITION)
			select @APPLICATION_ID,ORGANIZATION_NAME,TAX_ID_NUMBER,ADDRESS,FROM_DATE,TO_DATE,SALARY,SOCIAL_PAYMENT,POSITION
				from @COBORROWER_WORK_DATA
		end

		execute Common.sp_ChangeApplicationStatus @APPLICATION_ID,2

		update Common.APPLICATION
		set DOCUMENT_GIVEN_BY = @DOCUMENT_GIVEN_BY
			,DOCUMENT_GIVEN_DATE = @DOCUMENT_GIVEN_DATE
			,DOCUMENT_EXPIRY_DATE = @DOCUMENT_EXPIRY_DATE
		where ID = @APPLICATION_ID
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage varchar(4000)
		set @ErrorMessage = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
		RETURN
	END CATCH
	COMMIT TRANSACTION
GO
